"""docs/windows-autostart.md commands were verified on a non-admin Windows 11
shell; pin the properties that made them work so an edit cannot quietly
reintroduce the broken forms."""
import re

from bridge.config import REPO_ROOT

DOC = (REPO_ROOT / "docs" / "windows-autostart.md").read_text(encoding="utf-8")
BLOCKS = re.findall(r"```powershell\n(.*?)```", DOC, re.S)
TASK_BLOCKS = [b for b in BLOCKS if "Register-ScheduledTask" in b]


def test_no_admin_only_schtasks_logon_command():
    # schtasks /SC ONLOGON registers an any-user trigger: "Access is denied"
    # from a normal prompt, even with /RU.
    assert not any("schtasks /Create" in b for b in BLOCKS)


def test_task_commands_are_per_user_and_unlimited():
    # ComfyUI portable is the one task an operator still registers by hand.
    assert len(TASK_BLOCKS) == 1
    for block in TASK_BLOCKS:
        assert "-AtLogOn -User" in block
        # Task Scheduler's default 72h limit would stop a long-running worker.
        assert "-ExecutionTimeLimit ([TimeSpan]::Zero)" in block
        assert "-WorkingDirectory" in block


def test_bridge_crash_restart_uses_the_built_in_flag():
    # The watchdog task is generated by --restart-on-crash (bridge/service.py,
    # tested in test_service_install.py), not pasted by the operator.
    assert any(
        "--install-service --restart-on-crash" in b for b in BLOCKS
    )
    # "If the task fails, restart" does not fire when the program exits
    # nonzero; the doc must not promise it as the crash-restart mechanism.
    assert 'enable\n"If the task fails' not in DOC


def test_doc_explains_how_to_tell_the_bridge_is_down():
    assert "Bridge: NOT running" in DOC
    assert "exits with code 1" in DOC
